
name: lint
on: [push, pull_request, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff black mypy
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Mypy (type-check)
        run: mypy plasma_toolkit
